artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/vijaybalamahalingam/Red-Wine-Quality-Prediction-ML-Pipeline-Implementation/raw/refs/heads/main/WineQT.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

  